# 数据源配置
spring:
  datasource:
    name: newbee-mall-datasource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/newbee_mall_plus_db?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true&useAffectedRows=true
    username: root
    password: 1234

    hikari:
      pool-name: hikariCP
      minimum-idle: 100
      maximum-pool-size: 200
      auto-commit: true
      idle-timeout: 10000
      max-lifetime: 30000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:

    expire:400
  data:
    redis:
      host: 127.0.0.1
      client-type: lettuce
      connect-timeout: 5000ms
      timeout: 5000ms
      password:
      port: 6379

    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000ms
    connect-timeout: 5000ms
    expire: 400
    client-type: lettuce

