package ltd.newbee.mall.controller.admin;// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

public class OrderTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "D:\\geckodriver\\geckodriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void order() {
    try {
      driver.get("http://localhost:28079/admin/orders");
      driver.manage().window().setSize(new Dimension(1550, 830));

      WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
      WebElement element = wait.until(ExpectedConditions.visibilityOfElementLocated(By.cssSelector("#\\31 9842 > .jqgrid-multibox")));

      element.click();
      driver.findElement(By.cssSelector("#\\31 9842 a:nth-child(1)")).click();
      driver.findElement(By.cssSelector(".swal-button")).click();
      driver.findElement(By.cssSelector("#\\31 9839 a:nth-child(3)")).click();
      driver.findElement(By.cssSelector("#expressInfoModal .close")).click();
      driver.findElement(By.cssSelector(".btn-info:nth-child(1)")).click();
      driver.findElement(By.id("totalPrice")).click();
      driver.findElement(By.id("totalPrice")).sendKeys("6850");
      driver.findElement(By.id("saveButton")).click();
      driver.findElement(By.cssSelector(".swal-button")).click();
      driver.findElement(By.cssSelector(".btn-info:nth-child(2)")).click();
      {
        WebElement element1 = driver.findElement(By.cssSelector(".btn-info:nth-child(2)"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element1).perform();
      }
      {
        WebElement element1 = driver.findElement(By.tagName("body"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element1, 0, 0).perform();
      }
      driver.findElement(By.cssSelector(".swal-button--confirm")).click();
      driver.findElement(By.cssSelector(".swal-button")).click();
      driver.findElement(By.id("jqg_jqGrid_19842")).click();
      driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();
      {
        WebElement element1 = driver.findElement(By.cssSelector(".btn:nth-child(3)"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element1).perform();
      }
      {
        WebElement element1 = driver.findElement(By.tagName("body"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element1, 0, 0).perform();
      }
      driver.findElement(By.cssSelector(".swal-button--confirm")).click();
      driver.findElement(By.cssSelector(".swal-button")).click();
      driver.findElement(By.id("jqg_jqGrid_19842")).click();
      driver.findElement(By.cssSelector(".btn-danger")).click();
      {
        WebElement element1 = driver.findElement(By.cssSelector(".btn-danger"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element1).perform();
      }
      {
        WebElement element1 = driver.findElement(By.tagName("body"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element1, 0, 0).perform();
      }
      driver.findElement(By.cssSelector(".swal-button--confirm")).click();
      driver.findElement(By.cssSelector(".swal-button")).click();
    } catch (Exception e) {
      e.printStackTrace();
      System.out.println("Error: " + e.getMessage());
      System.out.println("Page Source: " + driver.getPageSource());
    }
  }
}
