package ltd.newbee.mall.controller.admin;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Test1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.gecko.driver", "C:\\Users\\cjh\\Downloads\\geckodriver-v0.34.0-win64\\geckodriver.exe");
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void test1() {
    driver.get("http://localhost:28079/admin/users");
    driver.manage().window().setSize(new Dimension(2576, 1408));

    // 显式等待元素可见
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(10));
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("jqg_jqGrid_15")));

    driver.findElement(By.id("jqg_jqGrid_15")).click();
    driver.findElement(By.id("jqg_jqGrid_14")).click();
    driver.findElement(By.cssSelector(".btn-danger")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".btn-danger"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".swal-button--confirm")).click();
    driver.findElement(By.cssSelector(".swal-button")).click();
    driver.findElement(By.id("jqg_jqGrid_15")).click();
    driver.findElement(By.cssSelector(".btn-info")).click();
    driver.findElement(By.cssSelector(".swal-button--confirm")).click();
    driver.findElement(By.cssSelector(".swal-button")).click();
    driver.findElement(By.cssSelector(".active > p")).click();
  }
}
